# Generated by Django 3.2.7 on 2021-09-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recog_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='attendance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='attendaceMark',
        ),
    ]
