# Generated by Django 3.2.7 on 2021-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recog_attendance', '0002_auto_20210914_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendanceMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_photo', models.ImageField(blank=True, null=True, upload_to='attendance')),
            ],
        ),
    ]
