# Generated by Django 3.2.7 on 2021-09-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recog_attendance', '0003_attendancemark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='call_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
