# Generated by Django 3.2.7 on 2021-09-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='decodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded', models.FileField(blank=True, null=True, upload_to='ecdc/encoded')),
            ],
        ),
        migrations.CreateModel(
            name='encodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('upload1', models.FileField(blank=True, null=True, upload_to='ecdc/decoded')),
                ('upload2', models.FileField(blank=True, null=True, upload_to='ecdc/main')),
            ],
        ),
    ]
