# Generated by Django 3.2.7 on 2021-09-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encode_decode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodefile',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
